name: MergeRecents 

on:

  workflow_dispatch:
  
  # scheduled run every Friday at 20.00 (19.00 UTC)
  schedule:
    - cron: '00 19 * * 1,5'
    
jobs:

  merge_recents_job:
    if: github.repository_owner == 'european-modelling-hubs'
    runs-on: ubuntu-latest
    steps:

    # Checkout the python tools repo
    # -------------------------------------------      
    - name: checkout python tools repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'european-modelling-hubs/hub-tools'
        ref: 'main'
        path: './tools/'

    # Checkout the data repository
    # -------------------------------------------      
    - name: checkout data repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'european-modelling-hubs/flu-forecast-hub'
        ref: 'main'
        path: './repo/'


    
    # Run Pyton code
    # -------------------------
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    
    # - run: pip install pandas==1.2.5 numpy==1.22.4
    
    - name: do the merge
      id: do_the_merge
      env:
        disease_name: ${{ vars.DISEASE_NAME }}
        
      run: |
        python ./tools/code/merge_recent_data.py --repository "./repo" --source_list "ERVISS FluID"

    - name: Commit data repo changes
      uses: EndBug/add-and-commit@v7
      with: 
          cwd: './repo'
          message: "Update data storage"
          default_author: github_actions
          push: true
